version: '3.9'

name: prod_portfolio_frontend

services:
  frontend-standalone:
    platform: linux/x86_64
    container_name: prod.nextjs.portfolio
    image: prod.nextjs.portfolio
    restart: unless-stopped
    ports:
      - '443:443'
    build:
      context: ../
      dockerfile: docker/prod.Dockerfile