version: '3.9'

name: prod_portfolio_frontend

services:
  portfolio_nextjs:
    platform: linux/x86_64
    container_name: portfolio_nextjs
    image: portfolio_nextjs
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/nextjs/prod.Dockerfile
    ports:
      - '3000:3000'
    networks:
      portfolio_net:
        aliases:
          - portfolio_nextjs
  portfolio_nginx:
    platform: linux/x86_64
    container_name: portfolio_nginx
    image: portfolio_nginx
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/nginx/prod.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - 'corentintruffaut.net:127.0.0.1'
      - 'www.corentintruffaut.net:127.0.0.1'
    networks:
      portfolio_net:
        aliases:
          - portfolio_nginx
networks:
  portfolio_net:
    name: portfolio_net

